# Generated by Django 2.1.2 on 2018-11-25 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('booking', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.Manager'),
        ),
    ]
